### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection. 

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#4]
```
klml@duck capc/ckan-tum [0] : ~/develop/opensource.muenchen.de
$ npm run docs:dev

> @ docs:dev /mnt/c/develop/opensource.muenchen.de
> vitepress dev

(node:418) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/mnt/c/develop/opensource.muenchen.de/node_modules/vitepress/bin/vitepress.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
klml@duck capc/ckan-tum [0] : ~/develop/opensource.muenchen.de
$ npm --version
6.14.4
klml@duck capc/ckan-tum [0] : ~/develop/opensource.muenchen.de
$ node --version
v10.19.0
```

**Comment by FabianWilms** [comment]
Vitepress requires

> [Node.js](https://nodejs.org/) version 18 or higher.
> 
> _https://vitepress.dev/guide/getting-started_

I tested it successfully with v16 but v10 ist definetly too old.

Could you please try it again with a newer version?

**Comment by klml** [comment]
```
klml@duck capc/udpkatalog-demo [0] : ~/develop/opensource.muenchen.de
$ node --version
v16.20.2
klml@duck capc/udpkatalog-demo [0] : ~/develop/opensource.muenchen.de
$ npm i
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/npm/lib/utils/unsupported.js
- /usr/share/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/npm/lib/utils/unsupported.js',
    '/usr/share/npm/bin/npm-cli.js'
  ]
}
```

**Comment by klml** [comment]
https://github.com/nodesource/distributions#ubuntu-versions helped me
